# Generated by Django 5.1.1 on 2024-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='data',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comentario',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='emoji',
            field=models.CharField(choices=[('bad', 'Insatisfeito'), ('neutral', 'Neutro'), ('good', 'Satisfeito'), ('excellent', 'Excelente')], max_length=20),
        ),
    ]
