# Generated by Django 5.1.1 on 2024-10-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0002_rename_data_feedback_created_at_and_more'),
    ]

    operations = [
    ]
